apiVersion: apps/v1
kind: Deployment
metadata:
  name: highlight-backend
spec:
  selector:
    matchLabels:
      app: highlight-backend
  template:
    metadata:
      labels:
        app: highlight-backend
    spec:
      containers:
      - name: highlight-backend
        image: arutji/highlight-backend
        ports:
        - name: http
          containerPort: 8000

