apiVersion: v1
kind: Service
metadata:
  name: highlight-backend
spec:
  selector:
    app: highlight-backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: backend-serivce-mapping
spec:
  host: api.highlight-project.dev
  prefix: /
  service: highlight-backend:80
  cors:
    origins: "*"
    credentials: true