apiVersion: v1
kind: Service
metadata:
  name: highlight-backend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: backend-serivce_mapping
      prefix: /
      service: highlight-backend:80
spec:
  selector:
    app: highlight-backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
