stages:
  - install
  - test
  - build  

install:frontend:
  image: node:10
  stage: install
  before_script:
    - cd frontend/
  script:
    - npm install
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/

build:frontend:
  image: node:10
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 60 mins
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
  needs: 
    - job: install:frontend

test:frontend:
  image: node:10
  stage: test
  before_script:
    - cd frontend/
  script:
  - npm run affected:test
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
  needs: 
    - job: install:frontend

build:documents:
  stage: build
  image: blang/latex
  script:
    - latexmk -pdf -cd doc/main.tex
  artifacts:
    paths:
      - "*.pdf"