image: nikolaik/python-nodejs:python3.7-nodejs12
stages:
  - test
  - build  

test:frontend:
  stage: test
  before_script:
    - cd frontend/
    - npm install
  script:
    - npm run test components
    - npm run test pwa-extension
    - npm run test chrome-extension

test:backend:
  stage: test
  before_script:
    - cd Base-setup
    - pipenv install --system
  script:
    - coverage erase
    - coverage run manage.py test
    - coverage report
  artifacts: 
    paths:
      - Base-setup/htmlcov
    expire_in: 60 mins

build:frontend-artifacts:
  stage: build
  before_script:
    - cd frontend/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 60 mins