stages:
  - install
  - test
  - build  

install:frontend:
  image: node:10
  stage: install
  before_script:
    - cd frontend/
  script:
    - npm install
  artifacts:
    name: "install:frontend"
    untracked: true
    expire_in: 60 mins
    paths: 
    - frontend/.npm/
    - frontend/node_modules/

build:frontend:
  image: node:10
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 60 mins
  needs: 
    - job: install:frontend
      artifacts: true

test:frontend:
  image: node:10
  stage: test
  before_script:
    - cd frontend/
  script:
  - npm run affected:test
  needs: 
    - job: install:frontend
      artifacts: true

build:documents:
  stage: build
  image: blang/latex
  script:
    - latexmk -pdf -cd doc/main.tex
  artifacts:
    paths:
      - "*.pdf"