version: '3'

services: 
  db:
    image: postgres
    restart: always
    volumes:
      - ./Base-setup/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=highlight-user
      - POSTGRES_PASSWORD=highlight
      - POSTGRES_DB=highlight
    networks:
      hilight:
        aliases:
          - db
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./Base-setup
    environment: 
      - DOCKER=1
      - DB_NAME=highlight
      - DB_USER=highlight-user
      - DB_PASSWORD=highlight
      - DB_HOST=db
      - DB_PORT=5432
    command: ['/bin/sh', './docker-entrypoint.sh']
    volumes:
      - ./Base-setup:/code
    ports:
      - "5000:8000"
    expose: 
      - 5000
    depends_on:
      - db
    networks:
      hilight:
        aliases:
          - backend
  pwa-extension:
    build:
      dockerfile: pwa-extension.Dockerfile
      context: ./frontend
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - backend
    links:
      - backend
    networks:
      hilight:
        aliases:
          - pwa-extension
networks:
  hilight: {}
