apiVersion: v1
kind: Service
metadata:
  name: highlight-frontend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend-serivce_mapping
      host: pwa.highlight-project.dev
      prefix: /
      service: highlight-frontend:80
spec:
  selector:
    app: highlight-frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
