# Generated by Django 2.1.5 on 2019-11-10 14:08

from django.db import migrations, models
import django.db.models.deletion
import highlights.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.CharField(default=highlights.models.hex_uuid, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('highlight_name', models.CharField(max_length=128)),
                ('highlight_script', models.CharField(max_length=1000)),
                ('comments', models.TextField()),
                ('startTime', models.FloatField(default=0.0)),
                ('endTime', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.CharField(default=highlights.models.hex_uuid, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('producer_name', models.CharField(max_length=128)),
                ('Logo_Picture', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('speaker_name', models.CharField(max_length=128)),
                ('speaker_description', models.CharField(blank=True, default='', max_length=128)),
                ('speaker_image', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugURL', models.CharField(default=highlights.models.hex_uuid, max_length=1000, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('typemedia', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], default='Video', max_length=400)),
                ('url', models.URLField()),
                ('video_description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('video_date', models.DateField(blank=True, default=highlights.models.today_utc, null=True)),
                ('comments', models.TextField()),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('video_producer', models.ForeignKey(blank=True, default='0fbd2ae21f', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Video_Producer', to='highlights.Producer')),
                ('video_speakers', models.ManyToManyField(blank=True, default='b781ef92-670c-4e74-b584-49fec58e9989', null=True, to='highlights.Speaker')),
            ],
            options={
                'ordering': ['-video_date'],
            },
        ),
        migrations.AddField(
            model_name='highlights',
            name='highlight_speakers',
            field=models.ManyToManyField(blank=True, default='b781ef92-670c-4e74-b584-49fec58e9989', null=True, to='highlights.Speaker'),
        ),
        migrations.AddField(
            model_name='highlights',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='highlights',
            name='videoID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Highlight_Video', to='highlights.Video'),
        ),
    ]
