version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  
    environment: 
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
  web:
    restart: always
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
