# Generated by Django 2.2.6 on 2019-11-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='text',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(blank=True)),
                ('comments', models.TextField()),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='highlights.Video')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
