# Generated by Django 2.2.6 on 2019-11-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0007_auto_20191110_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlights',
            name='videoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='highlights.Video'),
        ),
    ]
